### ISSUE TITLE
Running simple App on RHEL 7.3 64-bit. Error bash: ./test-log_linux_amd64: /lib/ld-musl-x86_64.so.1: bad ELF interpreter: No such file or directory

### ISSUE THREAD

**Issue by MMashalkar** [TIBCOSoftware/flogo#336] opened 2018-08-10 01:36 UTC
**Current behavior (how does the issue manifest):**

**Expected behavior:**

**Minimal steps to reproduce the problem (not required if feature enhancement):**

**Please tell us about your environment (Operating system, docker version, browser & web ui version, etc):**

**Flogo version (CLI & contrib/lib. If unknown, leave empty or state unknown):** 0.X.X

**Additional information you deem important (e.g. issue happens only occasionally):**

**Comment by MMashalkar** [comment] 2018-08-10 01:37
32-bit version works

**Comment by fm-tibco** [comment] 2018-08-10 01:40
Did you do the build from the WebUI?  If you did the build from the CLI,  did you build on that 64bit linux system or cross compiled from another system?

**Comment by retgits** [comment] 2018-08-10 02:13
If it is from the Web UI it is a known issue that we’re working on. The problem is that with recent Go builds CGO is enabled by default.  It’s likely the same as https://github.com/TIBCOSoftware/flogo/issues/313

**Comment by haarchri** [comment] 2018-09-25 09:28
the problem is fixed in the last build 0.5.6 - we tested with rhel7 is working now

**Comment by retgits** [comment] 2018-09-26 20:08
Closing as the issue is fixed

**Closed by retgits** 2018-09-26 20:08 UTC
